---
- hosts: all
  become: yes
  tasks:
  - name: nginx rpm download
    yum:
      name: http://nginx.org/packages/rhel/6/noarch/RPMS/nginx-release-rhel-6-0.el6.ngx.noarch.rpm
      state: present
  - name: install nginx
    yum:
      name: nginx
      state: present 
  - name: sevice start
    service:
      name: nginx
      state: started
      enabled: yes


