---
- hosts: webserver
  become: yes
  tasks:
  - name: download nodejs rpm 
    yum:
      name: https://rpm.nodesource.com/pub_4.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
      state: present
  - name: install nodejs
    yum:
      name: nodejs
      state: present
  - name: servce start
    service:
      name: nodejs
      state: started
      enabled: yes 
